### ISSUE TITLE
Underscore in url causes CRITICAL:twisted:Unhandled error in EventualResult

### ISSUE THREAD

**Issue by evenitz** [Yelp/fido#16]
In [9]: fido.fetch('https://fake_platform_partner-evenitz.dev.yelp.com/checkout_fulfillment/v2/check_availability', timeout=10, method='POST').result(timeout=10).body
CRITICAL:twisted:Unhandled error in EventualResult
Traceback (most recent call last):
  File "/nail/home/spatel/venv_crap/lib/python2.6/site-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/nail/home/spatel/venv_crap/lib/python2.6/site-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
  File "/nail/home/spatel/venv_crap/lib/python2.6/site-packages/twisted/internet/base.py", line 798, in runUntilCurrent
    f(_a, *_kw)
  File "/nail/home/spatel/venv_crap/lib/python2.6/site-packages/crochet/_eventloop.py", line 416, in runs_in_reactor
    d = maybeDeferred(function, _args, *_kwargs)
--- <exception caught here> ---
  File "/nail/home/spatel/venv_crap/lib/python2.6/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(_args, *_kw)
  File "/nail/home/spatel/venv_crap/lib/python2.6/site-packages/fido/fido.py", line 100, in fetch_inner
    bodyProducer=bodyProducer)
  File "/nail/home/spatel/venv_crap/lib/python2.6/site-packages/twisted/web/client.py", line 1559, in request
    endpoint = self._getEndpoint(parsedURI)
  File "/nail/home/spatel/venv_crap/lib/python2.6/site-packages/twisted/web/client.py", line 1543, in _getEndpoint
    return self._endpointFactory.endpointForURI(uri)
  File "/nail/home/spatel/venv_crap/lib/python2.6/site-packages/twisted/web/client.py", line 1419, in endpointForURI
    tlsPolicy = self._policyForHTTPS.creatorForNetloc(uri.host, uri.port)
  File "/nail/home/spatel/venv_crap/lib/python2.6/site-packages/twisted/web/client.py", line 876, in creatorForNetloc
    trustRoot=self._trustRoot)
  File "/nail/home/spatel/venv_crap/lib/python2.6/site-packages/twisted/internet/_sslverify.py", line 1233, in optionsForClientTLS
    return ClientTLSOptions(hostname, certificateOptions.getContext())
  File "/nail/home/spatel/venv_crap/lib/python2.6/site-packages/twisted/internet/_sslverify.py", line 1105, in __init__
    self._hostnameBytes = _idnaBytes(hostname)
  File "/nail/home/spatel/venv_crap/lib/python2.6/site-packages/twisted/internet/_sslverify.py", line 87, in _idnaBytes
    return idna.encode(text)
  File "/nail/home/spatel/venv_crap/lib/python2.6/site-packages/idna/core.py", line 354, in encode
    result.append(alabel(label))
  File "/nail/home/spatel/venv_crap/lib/python2.6/site-packages/idna/core.py", line 275, in alabel
    check_label(label)
  File "/nail/home/spatel/venv_crap/lib/python2.6/site-packages/idna/core.py", line 252, in check_label
    raise InvalidCodepoint('Codepoint {0} at position {1} of {2} not allowed'.format(_unot(cp_value), pos+1, repr(label)))
idna.core.InvalidCodepoint: Codepoint U+005F at position 5 of u'fake_platform_partner-evenitz' not allowed

**Comment by lucagiovagnoli** [comment]
This refers to a very old version of Fido (before 3.x.x). The CRITICAL errors in the EventualResult issue should be now fixed. Closing
